import { Metadata } from "next";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Icforu - Page not found",
  description: "Generated by create next app",
};

export default function NotFoundCatchAll() {
  notFound();
  
}
