import type { Metadata } from 'next';
import { Cairo, Inter } from 'next/font/google';
import { TLocale } from '@/i18n';
import Header from '@/components/Layout/Header';
import Footer from '@/components/Layout/Footer';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });
const cairo = Cairo({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'IC for U',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: TLocale };
}) {
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={`antialiased relative ${
          locale === 'ar' ? cairo.className : inter.className
        }`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
