import UnderConstructionPage from "@/components/Utils/UnderConstruction";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Icforu - Gates",
  description: "Generated by create next app",
};

export default function GatesPage() {
  return <UnderConstructionPage />;
}
